# Matrices

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import math
import pylab
import scipy.misc as sci

In [2]:
def suma_matrx(a,b):
    n = len(a)
    m = len(a[0])
    c = np.zeros((n,m))
    for i in range(n):
        for j in range(m):
            c[i][j] = a[i][j] + b[i][j]
    return c

In [3]:
a = [[0,1,0,3,4],[2,1,-1,1,1],[3,-1,-1,2,-3],[-1,2,3,-1,4]]
b = [[1,2,3,4,5],[7,-8,-1,3,1],[6,-1,-1,2,-3],[-1,2,3,-1,4]]

print(suma_matrx(a,b))

[[ 1.  3.  3.  7.  9.]
 [ 9. -7. -2.  4.  2.]
 [ 9. -2. -2.  4. -6.]
 [-2.  4.  6. -2.  8.]]


In [16]:
def mult_matrx(a,b):
    if len(a[0]) == len(b):
        n = len(a)
        m = len(a[0])
        p = len(b[0])
        c = np.zeros((n,p))
        for i in range(n):
            for j in range(p):
                ac = 0
                for k in range(m):
                    ac = ac + a[i][k]*b[k][j]
                c[i][j] = ac
        return c
    else: 
        print('LA MULTIPLICACIÓN DE LAS MATRICES NO SE PUEDE LLEVAR A CABO.\n')

In [18]:
A = [[2,1,-1],[3,1,2],[0.,-1,-3]]
B = [[3,2],[-1,1],[0,4]]
C = [[2,1,0.],[-1,3,2]]
D = [[1.,-1.,1.],[2.,-1.,2.],[3.,0.,3.]]

In [19]:
mult_matrx(A,D)

array([[  1.,  -3.,   1.],
       [ 11.,  -4.,  11.],
       [-11.,   1., -11.]])

In [20]:
mult_matrx(B,C)

array([[ 4.,  9.,  4.],
       [-3.,  2.,  2.],
       [-4., 12.,  8.]])

In [21]:
mult_matrx(B,A)

LA MULTIPLICACIÓN DE LAS MATRICES NO SE PUEDE LLEVAR A CABO.



In [22]:
def diag(a):   
    a = np.float32(np.array(a))
    for i in range(len(a)):
        for j in range(len(a)):
            if i < j:
                if a[i][i] == 0:
                    b = np.copy(a[i])
                    c = np.copy(a[j])
                    a[i] = c
                    a[j] = b
                if a[i][i] == 0:
                    a[j] = np.zeros(len(a[j]))
                    break
                a[j] =np.copy(a[j] - ((a[j][i]/a[i][i])*a[i]))
    return a

In [23]:
def solucion(a):
    c = diag(a)
    ac = 1
    n = len(c)
    for i in range(n):
        ac = ac*c[i][i]
    if ac == 0.:
        print('NO HAY SOLUCIÓN!!!')
    else:
        x = np.zeros(n)
        for i in range(n):
            ac = 0
            for j in range(n):
                ac = ac + c[n-1-i][n-1-j]*x[n-1-j]
            x[n-1-i] = (c[n-1-i][n]- ac)/c[n-1-i][n-1-i]
        return np.float32(x)

In [24]:
def inversa(a):
    a = np.float32(np.array(a))
    I = np.identity((len(a)))
    a_inv = []
    for i in range(len(I)):
        B = []
        B =  np.append(a,[I[i]],axis=0).T
        a_inv.append(solucion(B))
    return np.array(a_inv)

In [25]:
A = [[1,2,-1],[2,1,0.],[-1,1,2]]
A_inv = inversa(A)
print(A_inv)

[[-0.22222221  0.5555555  -0.11111113]
 [ 0.44444445 -0.1111111   0.22222222]
 [-0.33333334  0.33333334  0.33333334]]


In [26]:
B = np.round(mult_matrx(A,A_inv),1)
print(B)

[[ 1. -0. -0.]
 [ 0.  1. -0.]
 [-0.  0.  1.]]
