# Determinante:

Integrantes:

*De la Cruz Echeveste Oscar 

*Miranda Bustos Luis Fernando

*Obregon Ocampo Fernanda 

#### Calcular el determinante mediante diagonalización:

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import math
import pylab
import scipy.misc as sci

Hacemos una función que organice las matrices en forma de escalera inverza

In [2]:
def organizador(a):
    a = np.float32(np.array(a))
    n = len(a)
    m = len(a[0])
    c =  np.float32(np.zeros((n,m)))
    l = 0
    h = 0
    for j in range(m):
        l = 0
        p = h
        for i in range(n-p):
            if a[i+p][j] != 0:
                c[i-l+p] = a[i+p]
                h = h+1
            else:
                c[n-l-1] = a[i+p]
                l = l+1
        a = np.copy(c)
            
    return c

Definimos una función que diagonalice una matriz de nxn:

In [3]:
def diag(a):   
    a = np.copy(organizador(a))
    n = len(a)
    m = len(a[0])
    for i in range(m):
        for j in range(n):
            if i < j:
                a[j] =np.copy(a[j] - ((a[j][i]/a[i][i])*a[i]))
        a = np.copy(organizador(a))
    return a

In [4]:
def deter(a):
    c = diag(a)
    ac = 1
    for i in range(len(c)):
        ac = ac*c[i][i]
    return ac

#### Introducimos la matriz de la que queremos obtener el determinante (Aqui modificamos el código):

In [5]:
a = [[-1,2,3,-1,0],[0,1,0,0,1],[4,1,9,3,0],[-3,4,-2,1,1],[0,0,3,-1,2]]

In [6]:
print('La matriz extendida diagonalizada es:\n')
print(np.round(diag(a),2))
print('\nEl determinante de la matriz es:\n')
print(deter(a))

La matriz extendida diagonalizada es:

[[-1.00e+00  2.00e+00  3.00e+00 -1.00e+00  0.00e+00]
 [ 0.00e+00  1.00e+00  0.00e+00  0.00e+00  1.00e+00]
 [ 0.00e+00  0.00e+00 -1.10e+01  4.00e+00  3.00e+00]
 [ 0.00e+00  0.00e+00  0.00e+00  9.00e-02  2.82e+00]
 [ 0.00e+00  0.00e+00  0.00e+00  0.00e+00 -2.09e+02]]

El determinante de la matriz es:

-208.99999845025195
